### ISSUE TITLE
error trying to sub-class final class with cglib

### ISSUE THREAD

**Issue by Arnaud-Nauwynck** [ulisesbocchio/jasypt-spring-boot#111]
Hi,

I have these error when starting a project with springboot 2.1.0.RELEASE and jasypt-spring-boot-starter 2.1.0

Look simple to fix:  "if (Modifier.isFinal(class.getModifiers()) { ... do not try sub-class wth cglib ... } "

org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class org.springframework.boot.env.OriginTrackedMapPropertySource: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class org.springframework.boot.env.OriginTrackedMapPropertySource
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:208) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:155) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter.proxyPropertySource(EncryptablePropertySourceConverter.java:71) ~[jasypt-spring-boot-2.1.0.jar:na]

Regards,
Arnaud Nauwynck

**Comment by ulisesbocchio** [comment]
Ok, will take a look, thanks

**Comment by ulisesbocchio** [comment]
closing this, thanks @PierrePrimot
