### ISSUE TITLE
Decryption issue with PBEWithHMACSHA512AndAES_256 algorithm

### ISSUE THREAD

**Issue by muralimmk** [ulisesbocchio/jasypt-spring-boot#136]
`Exception in thread "main" org.jasypt.exceptions.EncryptionOperationNotPossibleException
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1055)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:725)
	at com.xxxx.xxxx.xxx.core.App.decrypt(App.java:42)
	at com.xxxx.xxxx.xxx.core.App.main(App.java:20)`

I am getting the above exception when I try to decrypt the encrypted format. Encryption works flawlessly. I read among the issues that 2.1.1 had a problem, so I am using 2.0.0. Please help.

**Comment by melloware** [comment]
I use 2.1.1 and it works fine.

Don't forget to set the IVgenerator property.

> The property jasypt.encryptor.ivGeneratorClassname defaults to NoOpIVGenerator for backwards compatibility. However, if you would like to use the newer algorithms in Java 8+ (e.g. PBEWITHHMACSHA512ANDAES_256) you must set this value to org.jasypt.salt.RandomIVGenerator

**Comment by ulisesbocchio** [comment]
thanks @melloware
