### ISSUE TITLE
Recursive Update

### ISSUE THREAD

**Issue by ismailseyfi** [ulisesbocchio/jasypt-spring-boot#158]
We are getting an exception with the most recent versions of boot starter and Java SDK 11 and 12 versions.  

Do you know what may be happening here? 

Caused by: java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1739)
	at org.springframework.cache.concurrent.ConcurrentMapCache.get(ConcurrentMapCache.java:144)
	at com.ulisesbocchio.jasyptspringboot.caching.CachingDelegateEncryptablePropertySource.getProperty(CachingDelegateEncryptablePropertySource.java:34)
	at com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty(EncryptableMapPropertySourceWrapper.java:31)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.find(SpringConfigurationPropertySource.java:111)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.find(SpringConfigurationPropertySource.java:100)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.getConfigurationProperty(SpringConfigurationPropertySource.java:84)
	at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.getConfigurationProperty(SpringIterableConfigurationPropertySource.java:68)
	at org.springframework.boot.context.properties.bind.Binder.findProperty(Binder.java:301)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:248)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:214)
	... 218 common frames omitted

**Comment by NikolajLeischner** [comment]
As a workaround, you may try to replace @ConfigurationProperties with @Value annotations; in my case this got rid of the recursion.

**Comment by ulisesbocchio** [comment]
There's PR to remove ConcurrentHashMap from the library. I'll merge/release soon

**Comment by ulisesbocchio** [comment]
fixed in 3.0.0
