### ISSUE TITLE
Algorithm “PBEWITHHMACSHA512ANDAES_256” not available，default Algorithm available

### ISSUE THREAD

**Issue by angiely1115** [ulisesbocchio/jasypt-spring-boot#174]
org.jasypt.exceptions.EncryptionOperationNotPossibleException
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.encrypt(StandardPBEByteEncryptor.java:1001)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.encrypt(StandardPBEStringEncryptor.java:655)
	at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.encrypt(PooledPBEStringEncryptor.java:465)
	at com.ulisesbocchio.jasyptspringboot.encryptor.DefaultLazyEncryptor.encrypt(DefaultLazyEncryptor.java:109)

**Comment by ulisesbocchio** [comment]
Not sure how to respond to this issue since all you did was to paste an exception...am I supposed to figure it out? 
Why don’t you explain the issue you’re facing and how to reproduce it?

**Comment by angiely1115** [comment]
my JVM configuration：
-Djasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256 -Djasypt.encryptor.iv-generator-classnam=org.jasypt.iv.RandomIvGenerator -Djasypt.encryptor.password=smart-framework -Djasypt.encryptor.provider-name=SunJCE

**Comment by angiely1115** [comment]
This configuration is available：
jasypt:
  encryptor:
   algorithm: PBEWITHHMACSHA512ANDAES_256
   ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator
   providerName: SunJCE
