### ISSUE TITLE
Property source doesn't exist (classpath:/bootstrap.properties) when using StandardEncryptableEnvironment with custom StringEncryptor

### ISSUE THREAD

**Issue by PavelKolobok** [ulisesbocchio/jasypt-spring-boot#193]
HI @ulisesbocchio! I'm using **spring-boot 2.2.0** and **spring-cloud-context 2.2.0** with **jasypt-spring-boot-starter 3.2.0** and having a problem.
If i use StandardEncryptableEnvironment with custom StringEncryptor:
```
StandardEncryptableEnvironment.builder()
.encryptor(new MyEncryptor())
.build();
```
then there is an exception after RefreshEvent:

`ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] (pool-22-thread-1) Unexpected error occurred in scheduled task: java.lang.IllegalArgumentException: PropertySource named 'applicationConfig: [classpath:/bootstrap.properties]' does not exist
        at org.springframework.core.env.MutablePropertySources.assertPresentAndGetIndex(MutablePropertySources.java:206)
        at org.springframework.core.env.MutablePropertySources.replace(MutablePropertySources.java:156)
        at com.ulisesbocchio.jasyptspringboot.aop.EncryptableMutablePropertySourcesInterceptor.invoke(EncryptableMutablePropertySourcesInterceptor.java:55)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.springframework.core.env.MutablePropertySources$$EnhancerBySpringCGLIB$$f3fa0e2d.replace(<generated>)
        at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:127)
        at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:93)
        at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:85)
        at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:72)
        at org.springframework.cloud.endpoint.event.RefreshEventListener.onApplicationEvent(RefreshEventListener.java:61)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)`

What can cause it?

**Comment by ulisesbocchio** [comment]
can you try version 3.0.3 that just went out?
