### ISSUE TITLE
Version3.0.2 was conflict with springfox-swagger

### ISSUE THREAD

**Issue by iHearty** [ulisesbocchio/jasypt-spring-boot#205]
`Caused by: java.lang.IllegalArgumentException: Found more then one function in BeanFactory: [inMemorySwaggerResourcesProvider, configPropsSingleton]. Consider providing 'spring.cloud.function.definition' property.
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.discoverDefaultDefinitionIfNecessary(BeanFactoryAwareFunctionRegistry.java:218) ~[spring-cloud-function-context-3.0.0.M3.jar:3.0.0.M3]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.compose(BeanFactoryAwareFunctionRegistry.java:246) ~[spring-cloud-function-context-3.0.0.M3.jar:3.0.0.M3]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:123) ~[spring-cloud-function-context-3.0.0.M3.jar:3.0.0.M3]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:111) ~[spring-cloud-function-context-3.0.0.M3.jar:3.0.0.M3]
	at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:72) ~[spring-cloud-function-context-3.0.0.M3.jar:3.0.0.M3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionChannelBindingInitializer.lambda$afterPropertiesSet$0(FunctionConfiguration.java:257) ~[spring-cloud-stream-3.0.0.M4.jar:3.0.0.M4]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_162]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionChannelBindingInitializer.afterPropertiesSet(FunctionConfiguration.java:255) ~[spring-cloud-stream-3.0.0.M4.jar:3.0.0.M4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 21 more`

**Comment by rupert-madden-abbott** [comment]
This looks like a specific incompatibility when using with both Spring Cloud Function and springfox-swagger.

The problem is that Spring Cloud Function will by default pick up any bean that implements Function, Consumer or Supplier. This library happens to declare a bean of type Supplier (configPropsSingleton) which Spring Cloud Function happens to be picking up.

Can you please try setting this (presuming that you want the Swagger bean to be picked up by Spring Cloud Function):

    spring.cloud.function.definition=inMemorySwaggerResourcesProvider
