### ISSUE TITLE
3.0.3 Starter can't work with SpringCloud 2020.0.1

### ISSUE THREAD

**Issue by FJiayang** [ulisesbocchio/jasypt-spring-boot#262]
When I tried to upgrade a Spring Cloud project from Hoxton.SR2 to 2020.0.1, it threw the following error. It worked well in the original Hoxton.SR2 version. Is there a solution?

I found that the origin of the problem is Spring Cloud recently added a CachedRandomPropertySource to add support for cached random values. 

https://github.com/spring-cloud/spring-cloud-commons/pull/719

envirment:
SpringCloud 2020.0.1
jasypt-spring-boot-starter 3.0.3

```
2021-02-11 17:44:38.573  INFO 17924 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=0437414b-f120-3a0e-8432-243df8b15dec
2021-02-11 17:44:38.589  INFO 17924 --- [           main] ptablePropertiesBeanFactoryPostProcessor : Post-processing PropertySource instances
2021-02-11 17:44:38.590  INFO 17924 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource cachedrandom [org.springframework.cloud.util.random.CachedRandomPropertySource] to EncryptablePropertySourceWrapper
2021-02-11 17:44:38.590  INFO 17924 --- [           main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource springCloudDefaultProperties [org.springframework.cloud.bootstrap.BootstrapApplicationListener$ExtendedDefaultPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2021-02-11 17:44:38.621 ERROR 17924 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: PropertySource named 'cachedrandom' does not exist
	at org.springframework.core.env.MutablePropertySources.assertPresentAndGetIndex(MutablePropertySources.java:228) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.core.env.MutablePropertySources.replace(MutablePropertySources.java:176) ~[spring-core-5.3.3.jar:5.3.3]
	at com.ulisesbocchio.jasyptspringboot.aop.EncryptableMutablePropertySourcesInterceptor.invoke(EncryptableMutablePropertySourcesInterceptor.java:49) ~[jasypt-spring-boot-3.0.3.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.core.env.MutablePropertySources$$EnhancerBySpringCGLIB$$f7b0bb1c.replace(<generated>) ~[spring-core-5.3.3.jar:5.3.3]
	at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter.lambda$convertPropertySources$1(EncryptablePropertySourceConverter.java:46) ~[jasypt-spring-boot-3.0.3.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_211]
	at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter.convertPropertySources(EncryptablePropertySourceConverter.java:46) ~[jasypt-spring-boot-3.0.3.jar:na]
	at com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor.postProcessBeanFactory(EnableEncryptablePropertiesBeanFactoryPostProcessor.java:41) ~[jasypt-spring-boot-3.0.3.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:178) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) [spring-boot-2.4.2.jar:2.4.2]
	at org.springblade.common.launch.JasyptBladeApplication.run(JasyptBladeApplication.java:29) [classes/:na]
	at org.springblade.auth.AuthApplication.main(AuthApplication.java:32) [classes/:na]

2021-02-11 17:44:38.625  WARN 17924 --- [       Thread-9] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2021-02-11 17:44:38.626  WARN 17924 --- [       Thread-9] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end

```

**Comment by kheckelmann** [comment]
Hi - did you find the reason for your problem? I get the same error when I try to use StandardEncryptableEnvironment and I don't really know what I'm doing wrong.

**Comment by CarlosUJED** [comment]
me too any hints on this?

**Comment by ulisesbocchio** [comment]
3.0.4 released
