### ISSUE TITLE
Problem with spring-cloud-config and refresh

### ISSUE THREAD

**Issue by kheckelmann** [ulisesbocchio/jasypt-spring-boot#267]
Hi,

I have a problem with jasypt and the actuator refresh endpoint. 

Versions:
spring boot: 2.3.9
spring cloud: Hoxton.SR10
jasypt: 3.0.3

Originally we integrated jasypt by adding the jasypt-spring-boot dependency and adding the @EnableEncryptableProperties to a configuration class. This worked as expected on initial startup of the application. We have some encrypted properties that are provided by the spring cloud config server and they are correctly decrypted and used.

But triggering the refresh without changing the configuration files results in changes to this encrypted properties and inspecting them shows that after the refresh they are filled with the encrypted value instead of the decrypted one. Searching for this issue, I found some recommendations to use the StandardEncryptableEnvironment with the SpringApplicationBuilder. I tried it, but with the StandardEncryptableEnvironment our application is no longer booting. I get this error: 

```
java.lang.IllegalArgumentException: PropertySource named 'cachedrandom' does not exist
	at org.springframework.core.env.MutablePropertySources.assertPresentAndGetIndex(MutablePropertySources.java:228)
	at org.springframework.core.env.MutablePropertySources.replace(MutablePropertySources.java:176)
	at com.ulisesbocchio.jasyptspringboot.aop.EncryptableMutablePropertySourcesInterceptor.invoke(EncryptableMutablePropertySourcesInterceptor.java:49)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.springframework.core.env.MutablePropertySources$$EnhancerBySpringCGLIB$$8afbdedf.replace(<generated>)
	at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter.lambda$convertPropertySources$1(EncryptablePropertySourceConverter.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySourceConverter.convertPropertySources(EncryptablePropertySourceConverter.java:46)
	at com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor.postProcessBeanFactory(EnableEncryptablePropertiesBeanFactoryPostProcessor.java:41)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:291)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:175)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
```
	
I debugged it a little and found out that the replace is actually done twice in the EncryptableMutablePropertySourcesInterceptor, once for the envCopy and once for the normal MutablePropertySources and in the envCopy the cachedrandom part was missing. In fact, the envCopy had only 16 property sources while the other MutablePropertySources had 19. The missing ones were the bootstrap.yml files and this cachedrandom property source.

I first thought I might be able to circumvent the issue by adding it to the skipPropertySourceClasses but this did not help, because in EncryptablePropertySourceConverter.convertPropertySources the filter only checks if it is not an instance of EncryptablePropertySource. The skipPropertySourceClasses check is only done in the makeEncrypable method, so it still tries to replace the property source with itself.

My next idea was that maybe it is not a good idea to mix the StandardEncryptableEnvironment and the @EnableEncryptableProperties annotation, so I removed the annotation. With this change, I was able to start the application again. However, trying to call refresh results in an exception again: 

```
java.lang.IllegalArgumentException: PropertySource named 'applicationConfig: [classpath:/config/bootstrap-dev.yml]' does not exist
	at org.springframework.core.env.MutablePropertySources.assertPresentAndGetIndex(MutablePropertySources.java:228)
	at org.springframework.core.env.MutablePropertySources.replace(MutablePropertySources.java:176)
	at com.ulisesbocchio.jasyptspringboot.aop.EncryptableMutablePropertySourcesInterceptor.invoke(EncryptableMutablePropertySourcesInterceptor.java:49)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.springframework.core.env.MutablePropertySources$$EnhancerBySpringCGLIB$$8afbdedf.replace(<generated>)
	at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:127)
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:93)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:85)
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

```
Now I'm having only 19 entries in the envCopy but 21 in the wrapping MutablePropertySources. The missing ones are the bootstrap files plus the cachedrandom one from the error before. The difference is probably that this property sources belong to the bootstrap context.

I'm not sure if I'm doing something wrong, I'm a little out of ideas right now, so any hints how to solve this problem are appreciated.

Thank you
Kristina

**Comment by ulisesbocchio** [comment]
Yeah, I hear you, something changed in Spring Boot 3 that's wrapping properties sources in a `ConfigurationPropertySourcesPropertySource` that's causing jasypt-spring-boot to wrap the property source classes twice. I've been working on a fix but I haven't had the time to fix it. I'll keep you posted. In the meantime if you know which class is the one being wrapped twice that's failing you can try skipping it: https://github.com/ulisesbocchio/jasypt-spring-boot#filter-out-propertysource-classes-from-being-introspected

**Comment by kheckelmann** [comment]
I tried skipping at least the CachedRandomPropertySource but it didn't make any difference. In EncryptablePropertySourceConverter.convertPropertySources the filter only skips the replacement if it is not an instance of EncryptablePropertySource. The skipPropertySourceClasses check is only done in the makeEncryptable method, so it still tries to replace the property source - not with a wrapper but with itself. In the end I got the same error. 

But even if it would work, I don't think I can skip the bootstrap file sources, they are not of a specific class. 

In the end, I think the target MutablePropertiesSources should contain the same property sources as the envCopy, just wrapped - I'm still not sure what happens for them to diverge.

**Comment by tomaszrichert** [comment]
I only now see that you have similar issue that I've just described here: https://github.com/ulisesbocchio/jasypt-spring-boot/issues/269
I used @ulisesbocchio  advice and added:
jasypt.encryptor.skip-property-sources=org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource
which works well for me at least until we have a proper fix.

**Comment by ulisesbocchio** [comment]
3.0.4 released
