### ISSUE TITLE
Upgrade uk.org.webcompere:system-stubs-jupiter so the project can be built with JDK 16+.

### ISSUE THREAD

**Issue by paul-kraftlauget** [ulisesbocchio/jasypt-spring-boot#330]
The uk.org.webcompere:system-stubs-jupiter test library should be upgrade so that the project can be built with JDK 16+.

For more information, see https://github.com/webcompere/system-stubs

For example, trying to build with JDK 17 gives this error:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @16b4a017

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at uk.org.webcompere.systemstubs.environment.EnvironmentVariables.getFieldValue(EnvironmentVariables.java:243)
        ...
```

Upgrading the library to 2.x.x fixes the build failure.

**Comment by matthenry87** [comment]
If accepted+merged, [this PR](https://github.com/ulisesbocchio/jasypt-spring-boot/pull/341) will include this change.
