### ISSUE TITLE
versions 3.0.4  and 3.0.5 throw java.lang.NoClassDefFoundError: ch/qos/logback/core/util/ContextUtil

### ISSUE THREAD

**Issue by dbnex14** [ulisesbocchio/jasypt-spring-boot#347]
I am using spring-boot-starter-parent version 2.7.6

Same issue described below happens with **jasypt-spring-boot-starter** dependency  3.0.4 and 3.0.5

Added in pom.xml of my Spring Boot app
```
		<dependency>
			<groupId>com.github.ulisesbocchio</groupId>
			<artifactId>jasypt-spring-boot-starter</artifactId>
			<version>3.0.5</version>
		</dependency>
```

Added plugin:
```
<build>
   <plugins>
        ....

	<plugin>
		 <groupId>com.github.ulisesbocchio</groupId>
		 <artifactId>jasypt-maven-plugin</artifactId>
		 <version>3.0.5</version>
	</plugin>
   </plugins>
```

Annotated my spring boot class

```
@EnableEncryptableProperties
@SpringBootApplication
public class MyApiApplication {
	public static void main(String[] args) {...}
}
```

Issuing:
`mvn jasypt:encrypt-value -Djasypt.encryptor.password=mysecret -Djasypt.plugin.value=valuetoencrypt`

Exception in thread "SpringApplicationShutdownHook" java.lang.NoClassDefFoundError: ch/qos/logback/core/util/ContextUtil
        at ch.qos.logback.core.FileAppender.stop(FileAppender.java:146)
        at ch.qos.logback.core.rolling.RollingFileAppender.stop(RollingFileAppender.java:149)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.detachAndStopAllAppenders(AppenderAttachableImpl.java:107)
        at ch.qos.logback.classic.Logger.detachAndStopAllAppenders(Logger.java:206)
        at ch.qos.logback.classic.Logger.recursiveReset(Logger.java:331)
        at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:223)
        at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:348)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$getShutdownHandler$0(LogbackLoggingSystem.java:284)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:116)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.util.ContextUtil
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

**Comment by pwils025** [comment]
Any update on this issue?

**Comment by dbnex14** [comment]
I decided to move on and not use jasypt at all

**Comment by AsrafulAsif** [comment]
> I decided to move on and not use jasypt at all

then what should you use ?

**Comment by ulisesbocchio** [comment]
It looks like you have a version mismatch between logback core and spring. Or you don’t have logback core at all in the classpath

**Comment by dbnex14** [comment]
> > I decided to move on and not use jasypt at all
> 
> then what should you use ?

In our case, developers deploy apps to their local container.
Infrastructure deploys to their Ava devs have no visibility to infrastructure containers.  For that reason, we use nothing sunce credentials used on our local containers are test credentials and are different from the ones used by infrastructure teams.
So as long as we have same keys, the values app uses are unimportant.
As a container we use OpenLiberty but that is unimportant.
So, I have my local, in jar application.yml with key/value settings so uses ifrun in embedded tomcat.
I do the same application.yml file in the root of my local OpenLiberty root or root/config directory ABS spring will auto pick it up from there and override in jar application.yml (or properties). This overwrites application.yml in jar.
Infrastructure team does the same but change sensitive credentials etc to values only they know hence no need for this library.
So, I might have password =test but infrastructure can have password =xyz4583fh for example and developers don’t know it.
Google for ConfigurationProperties annotation in spring boot for this if you are not familiar.  It explains how to externalizer your properties which is what I explained above.
Hope that helps.

**Comment by AsrafulAsif** [comment]
can you provide some articles regarding the solution, It really helps for us who need ??

**Comment by dbnex14** [comment]
> can you provide some articles regarding the solution, It really helps for us who need ??



> can you provide some articles regarding the solution, It really helps for us who need ??

Yes, Google for ConfigurationProperties .  As I explained above, that will help you

**Comment by AsrafulAsif** [comment]
thanks man!!

**Comment by syedshabbir** [comment]
Seems you can disable logging shutdown as below

` ./mvnw jasypt:encrypt-value -Djasypt.encryptor.password=password -Dlogging.register-shutdown-hook=false -Djasypt.plugin.value=secret`

preventing output 
Exception in thread "SpringApplicationShutdownHook" java.lang.NoClassDefFoundError: ch/qos/logback/core/util/ContextUtil
	at ch.qos.logback.core.FileAppender.stop(FileAppender.java:146)
	at ch.qos.logback.core.rolling.RollingFileAppender.stop(RollingFileAppender.java:149)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.detachAndStopAllAppenders(AppenderAttachableImpl.java:107)
	at ch.qos.logback.classic.Logger.detachAndStopAllAppenders(Logger.java:206)
	at ch.qos.logback.classic.Logger.recursiveReset(Logger.java:331)
	at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:223)
	at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:348)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$getShutdownHandler$0(LogbackLoggingSystem.java:284)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:116)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.util.ContextUtil
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)

**Comment by BearKid** [comment]
I'm using jasypt-maven-plugin:3.0.5, and I've encountered this error as well, though it doesn't affect the core functionality.
I found that I can reproduce this issue by adding this minimal configuration to application.yml:
```
logging:
  file:
    name: 'whatever.log'
```
