### ISSUE TITLE
proxy-property-sources=true causes ClassCastException

### ISSUE THREAD

**Issue by greenarr0w** [ulisesbocchio/jasypt-spring-boot#369]
Hello

I'm trying to use `jasypt.encryptor.proxy-property-sources=true` so that the PropertySources aren't wrapped, only proxied. We need this in our setup, because our internal framework has wrapped those PropertySources.

Versions:
jasypt-spring-boot-starter:3.0.5
org.springframework.boot:2.7.14

Now I'm getting the following ClassCastException. The exception happens with a plain spring boot app with the jasypt-spring-boot-starter (first I thought it has something to do with our setup, but it doesn't seem like it):
```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'servletWebServerFactoryCustomizer' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is java.lang.ClassCastException: class org.springframework.core.env.PropertiesPropertySource cannot be cast to class com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource (org.springframework.core.env.PropertiesPropertySource and com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource are in unnamed module of loader 'app')
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.29.jar:5.3.29]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.14.jar:2.7.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.14.jar:2.7.14]
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:13) ~[main/:na]
```

```
nested exception is java.lang.ClassCastException: class org.springframework.core.env.PropertiesPropertySource cannot be cast to class com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource 
```

Is this a known issue or is there a way to fix it?

Thank you in advance.

**Comment by LemonNanami** [comment]
This might be same problem.
I don't find any known issue or is there a way to fix it, but when I set proxy-property-sources=false it works.
`Caused by: org.springframework.aop.AopInvocationException: AOP configuration seems to be invalid: tried calling method [public default boolean com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.isImmutable()] on target [PropertiesPropertySource {name='systemProperties'}]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at com.ulisesbocchio.jasyptspringboot.aop.EncryptablePropertySourceMethodInterceptor.invoke(EncryptablePropertySourceMethodInterceptor.java:42)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at org.springframework.core.env.PropertiesPropertySource$$SpringCGLIB$$0.isImmutable(<generated>)
	at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.isImmutablePropertySource(SpringIterableConfigurationPropertySource.java:173)
	at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.<init>(SpringIterableConfigurationPropertySource.java:66)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.from(SpringConfigurationPropertySource.java:149)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources.adapt(SpringConfigurationPropertySources.java:69)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:124)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:119)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.hasNext(SpringConfigurationPropertySources.java:94)
	at org.springframework.boot.context.properties.bind.Binder.<init>(Binder.java:186)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.getBinder(ConfigurationPropertiesBinder.java:181)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:94)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:96)
	... 52 common frames omitted
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	... 74 common frames omitted
`
![Uploading fpD2lHEFJr.jpg…]()

**Comment by LemonNanami** [comment]
I might have got the same problem. When I set proxy-property-sources=true, I find a AOP configuration exception while invoking method  com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.isImmutable() with PropertiesPropertySource.
I havn't find any  known issue about, but when I set proxy-property-sources=true it works.

`Caused by: org.springframework.aop.AopInvocationException: AOP configuration seems to be invalid: tried calling method [public default boolean com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.isImmutable()] on target [PropertiesPropertySource {name='systemProperties'}]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at com.ulisesbocchio.jasyptspringboot.aop.EncryptablePropertySourceMethodInterceptor.invoke(EncryptablePropertySourceMethodInterceptor.java:42)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at org.springframework.core.env.PropertiesPropertySource$$SpringCGLIB$$0.isImmutable(<generated>)
	at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.isImmutablePropertySource(SpringIterableConfigurationPropertySource.java:173)
	at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.<init>(SpringIterableConfigurationPropertySource.java:66)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.from(SpringConfigurationPropertySource.java:149)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources.adapt(SpringConfigurationPropertySources.java:69)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:124)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:122)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.fetchNext(SpringConfigurationPropertySources.java:119)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySources$SourcesIterator.hasNext(SpringConfigurationPropertySources.java:94)
	at org.springframework.boot.context.properties.bind.Binder.<init>(Binder.java:186)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.getBinder(ConfigurationPropertiesBinder.java:181)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:94)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:96)
	... 52 common frames omitted
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	... 74 common frames omitted`
![20240221-103130](https://github.com/ulisesbocchio/jasypt-spring-boot/assets/65717722/497e0370-da7b-43c1-b006-b062a8a5b5e0)
