### ISSUE TITLE
 jasypt-spring-boot-starter-3.0.5 does not work with springboot latest version 3.2.2

### ISSUE THREAD

**Issue by siddhuReddy15906** [ulisesbocchio/jasypt-spring-boot#386]
here is my dependencies

 1.       <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot</artifactId>
            <version>3.0.5</version>
        </dependency>

2.
               <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.2.2</version>

error :
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'enableEncryptablePropertySourcesPostProcessor' defined in class path resource [com/ulisesbocchio/jasyptspringboot/configuration/EnableEncryptablePropertiesConfiguration.class]: Unsatisfied dependency expressed through method 'enableEncryptablePropertySourcesPostProcessor' parameter 0: Cannot find class [org.springframework.web.servlet.view.tiles3.TilesConfigurer] for bean with name 'tilesConfigurer' defined in class path resource [appServlet.xml]

lookin for answers, tried changing jasypt versions but not worked

**Comment by duke2048** [comment]
Same issue here, when I upgraded to SpringBoot 3.1.12 with SpringCore 6.1.12. My app doesn't start anymore, any clues how to fix it?

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'enableEncryptablePropertySourcesPostProcessor' defined in class path resource [com/ulisesbocchio/jasyptspringboot/configuration/EnableEncryptablePropertiesConfiguration.class]: Unsatisfied dependency expressed through method 'enableEncryptablePropertySourcesPostProcessor' parameter 0: Invalid bean definition with name 'demoRepository' defined in com.demo.dao.DemoRepository defined in @EnableJpaRepositories declared on DatabaseConfig: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:542)```

**Comment by Karthikrajaskr** [comment]
Hi Siddhu,
Same issue with my project as well.. Any fix you could suggest ?

**Comment by BilgehanYildiz** [comment]
@neonleo 
@duke2048 @Karthikrajaskr  does anyone find a workaround?

**Comment by duke2048** [comment]
In my case I was using an older version of spring-jpa, upgrading to latest solved the issue for me.

**Comment by japzio** [comment]
facing same issue when upgrading from 3.1.X to 3.5.X.
